apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/webapp.yaml

namespace: "zyproj"

namePrefix: "user01-"
nameSuffix: "-dev"

images:
  - name: "nginx"
    newName: "nginx"
    newTag: "1.28"

labels:
  - pairs:
      app.kubernetes.io/owner: "user01"
      app.kubernetes.io/name: "nginx28"
    includeSelectors: true
    includeTemplates: true

patches:
  - target:
      kind: Deployment
      name: web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
